#Export("platform")
#print("hi")

Import("platform")
Import("env")
Import("build_dir")

Export("platform")
Export("env")
Export("build_dir")

Import("libilmath")
Export("libilmath")

SConscript("math/SConscript")
Default(None)

