#!/bin/sh

version=$(git describe --tags --all | tr -d '\n')
commit=$(git rev-parse HEAD | tr -d '\n')

echo '// Automatically generated by tup'
echo 'const char il_version[] = "'$version'";'
echo 'const char il_commit[] = "'$commit'";'
echo 'const char il_build_date[] = __DATE__;'
