#!/bin/sh

echo '// Automatically generated by tup'
echo -n 'const char il_version[] = "'
git describe --tags --all | tr -d '\n'
echo '";'
echo -n 'const char il_commit[] = "'
git rev-parse HEAD | tr -d '\n'
echo '";'
echo 'const char il_build_date[] = __DATE__;'
