import os

output    = "libilutil"
src_dir   = "#src/util"
build_dir = "#build"
inputs    = "*.c #src/windows.c"

Import("platform")
Import("env")

util = env.Clone()

util.Append(CPPPATH = src_dir)

sources = []
for module in Split(inputs) :
    sources.extend(Glob(module))

libilutil= util.SharedLibrary(target = build_dir + "/" + output, 
                              source = sources)

Return("libilutil")

