import os

output    = "libilutil"
src_dir   = "#src/util"
build_dir = "#build"
inputs    = "*.c"

Import("platform")
Import("env")

util = env.Clone()

util.Append(CPPPATH = src_dir)

sources = []
for module in Split(inputs) :
    sources.extend(Glob(module))

objects = util.Object(source = sources)

libilutil= util.StaticLibrary(target = build_dir + "/" + output, 
                              source = objects)

Return("libilutil")

