import os

output    = "libilasset"
src_dir   = "#src/asset"
build_dir = "#build"
inputs    = "*.c"

Import("platform")
Import("env")
Import("libilutil")
#Import("libilmath")
#Import("libilcommon")

asset = env.Clone()

asset.Append(CPPPATH = src_dir)

pkg_libs = {
    "osx":   ["libglfw", "glew"],
    "arch":  ["libglfw", "glew", "gl"],
    "linux": ["gl", "glfw", "glew"],
}

if platform=="mingw":
    asset.Append(LIBS=["-lilutil", "glfw", "glew32", "opengl32", "png", "z"])
else:
    asset.Append(LIBS=["png", "-lilutil"])
    for lib in pkg_libs[platform]:
        asset.ParseConfig("pkg-config " + lib + " --cflags --libs")


sources = []
for module in Split(inputs) :
    sources.extend(Glob(module))

libilasset = asset.SharedLibrary(target = build_dir + "/" + output, 
                                       source = sources)
Depends(libilasset, libilutil)
#Depends(libilasset, libilmath)
#Depends(libilasset, libilcommon)

Return("libilasset")

