#ifndef ILG_FRAGDATA_H
#define ILG_FRAGDATA_H

enum ilG_fragdata {
    ILG_FRAGDATA_ACCUMULATION,
    ILG_FRAGDATA_NORMAL,
    ILG_FRAGDATA_DIFFUSE,
    ILG_FRAGDATA_SPECULAR,
    ILG_FRAGDATA_SPECULAR_CO,
    ILG_FRAGDATA_NUMATTRS
};

#endif
