import os

output    = "mathtest"
src_dir   = "#test/math"
inputs    = "*.c"

Import("build_dir")
Import("platform")
Import("env")
Import("libilmath")

sources = []
for module in Split(inputs) :
    sources.extend(Glob(src_dir + "/" + module))

testenv = env.Clone()
testenv.Append(LIBS=["-lilmath","-lilutil","-lm"])
if platform != 'mingw':
    testenv.Append(LIBS=['-ldl'])

objects = testenv.Object(source = sources)

mathtest = testenv.Program(target = build_dir + "/" + output, 
                       source = objects)
Depends(mathtest, libilmath)

Return("mathtest")

