import os

output    = "libilmath"
src_dir   = "#src/math"
build_dir = "#build"
inputs    = "*.c"

Import("platform")
Import("env")

ilmath = env.Clone()

ilmath.Append(CPPPATH = src_dir)

sources = []
for module in Split(inputs) :
    sources.extend(Glob(module))

objects = ilmath.Object(source = sources)

libilmath = ilmath.StaticLibrary(target = build_dir + "/" + output, 
                              source = objects)

Return("libilmath")

