import os

output    = "libilmath"
src_dir   = "#src/math"
inputs    = "*.c"

Import("build_dir")
Import("platform", "env")

ilmath = env.Clone()

ilmath.Append(CPPPATH = src_dir, LIBS=[])

sources = []
for module in Split(inputs) :
    sources.extend(Glob(module))

#objects = ilmath.Object(source = sources)

libilmath = ilmath.SharedLibrary(target = build_dir + "/" + output,
                                 source = sources) #objects)

Return("libilmath")
