#!/bin/sh

echo '// Automatically generated by tup'
echo -n 'static const char il_version[] = "'
#git describe --dirty --tags --all | tr -d '\n'
echo '";'
echo -n 'static const char il_commit[] = "'
git rev-parse HEAD | tr -d '\n'
echo '";'
