import os

output    = "libilcommon"
src_dir   = "#src/common"
inputs    = "*.c"

Import("build_dir")
Import("platform")
Import("env")
Import("libilutil")
Import("libilmath")

common = env.Clone()

common.Append(CPPPATH = src_dir, LIBS=['ilutil', 'ilmath'])

sources = []
for module in Split(inputs) :
    sources.extend(Glob(module))

libilcommon = common.SharedLibrary(target = build_dir + "/" + output,
                                   source = sources)
Depends(libilcommon, libilutil)
Depends(libilcommon, libilmath)

Return("libilcommon")
