import os

output    = "libilinput"
src_dir   = "#src/input"
build_dir = "#build"
inputs    = "*.c"

Import("platform")
Import("env")
Import("libilutil")
Import("libilcommon")

inputenv = env.Clone()

inputenv.Append(CPPPATH = src_dir, LIBS=['ilutil', 'ilcommon'])

sources = []
for module in Split(inputs) :
    sources.extend(Glob(module))

libilinput = inputenv.SharedLibrary(target = build_dir + "/" + output, 
                                   source = sources)
Depends(libilinput, libilutil)
Depends(libilinput, libilcommon)

Return("libilinput")

